
import { Subject, Topic, Challenge, Stream } from '../types';

export const ALL_SUBJECTS: Subject[] = ['Math', 'Physics', 'Chemistry', 'CS', 'Biology', 'Economics', 'Business Studies', 'Accountancy', 'History', 'Geography', 'Political Science'];

const MATH_TOPICS: Topic[] = [
    {
        id: 'm-topic-calculus-basics', name: 'Calculus Basics', description: 'The art of change and accumulation.',
        challenges: [
            { id: 'm-cb-1', answer: "f'(x) = 15x^4", description: "The original function was f(x) = 3x^5. Explain how the power rule is used to find this derivative.", difficulty: 'Easy' },
            { id: 'm-cb-2', answer: "The limit is 9", description: "The expression was lim(x->3) of (x^2). Explain why direct substitution works here.", difficulty: 'Easy' },
            { id: 'm-cb-3', answer: "f'(x) = cos(x)", description: "The original function was f(x) = sin(x). What is the fundamental derivative of this trigonometric function?", difficulty: 'Easy' },
            { id: 'm-cb-4', answer: "The integral is x^3 + C", description: "The function being integrated was 3x^2. Explain the reverse power rule for integration.", difficulty: 'Easy' },
            { id: 'm-cb-5', answer: "f'(x) = 5", description: "The original function was f(x) = 5x - 2. Explain why the derivative of a linear function is its slope.", difficulty: 'Easy' },
            { id: 'm-cb-6', answer: "f'(x) = 2x + 3", description: "The original function was f(x) = x^2 + 3x + 7. Explain how the sum rule for derivatives is applied.", difficulty: 'Medium' },
            { id: 'm-cb-7', answer: "f'(x) = e^x", description: "The original function was f(x) = e^x. Why is this function unique in calculus?", difficulty: 'Medium' },
            { id: 'm-cb-8', answer: "The area is 26/3", description: "This is the result of the definite integral of x^2 from x=1 to x=3. Explain the steps using the Fundamental Theorem of Calculus.", difficulty: 'Medium' },
            { id: 'm-cb-9', answer: "f'(x) = 3cos(3x)", description: "The original function was f(x) = sin(3x). Explain how the chain rule is used here.", difficulty: 'Medium' },
            { id: 'm-cb-10', answer: "The slope is 4", description: "This is the slope of the tangent line to the curve y = x^2 at the point (2, 4). How is the derivative used to find this?", difficulty: 'Medium' },
            { id: 'm-cb-11', answer: "f'(x) = 2x*cos(x) - x^2*sin(x)", description: "The original function was f(x) = x^2*cos(x). Explain how the product rule for derivatives is applied.", difficulty: 'Hard' },
            { id: 'm-cb-12', answer: "The integral is (1/2)sin(x^2) + C", description: "The function being integrated was x*cos(x^2). Explain how u-substitution is used to solve this.", difficulty: 'Hard' },
            { id: 'm-cb-13', answer: "f'(x) = 1/x", description: "The original function was f(x) = ln(x). What is the derivative of the natural logarithm function?", difficulty: 'Medium' },
            { id: 'm-cb-14', answer: "The second derivative is 6x", description: "The original function was f(x) = x^3 + 2x. Explain the process of finding the second derivative and what it represents (concavity).", difficulty: 'Hard' },
            { id: 'm-cb-15', answer: "A local maximum occurs at x=0", description: "The function is f(x) = -x^2 + 5. Explain how the first derivative test is used to identify this local maximum.", difficulty: 'Medium' },
            { id: 'm-cb-16', answer: "The limit does not exist.", description: "The expression was lim(x->0) of (1/x). Explain why this limit fails to exist.", difficulty: 'Medium' },
            { id: 'm-cb-17', answer: "f'(x) = (cos(x)*x - sin(x)) / x^2", description: "The original function was f(x) = sin(x) / x. Explain the quotient rule for derivatives.", difficulty: 'Hard' },
            { id: 'm-cb-18', answer: "The average value is 4", description: "This is the average value of the function f(x) = 3x^2 on the interval [0, 2]. Explain the formula for the average value of a function.", difficulty: 'Hard' },
            { id: 'm-cb-19', answer: "The function is not continuous at x=2", description: "The function was a piecewise function defined as f(x) = x+1 for x<2, and f(x) = x^2 for x>=2. Explain the conditions for continuity.", difficulty: 'Medium' },
            { id: 'm-cb-20', answer: "The volume is 16π/15", description: "This is the volume of the solid generated by revolving the region bounded by y=x^2 and y=x about the x-axis. Explain the washer method for finding volumes of revolution.", difficulty: 'Hard' }
        ]
    },
    {
        id: 'm-topic-linear-algebra', name: 'Linear Algebra', description: 'The study of vectors, spaces, and linear transformations.',
        challenges: [
            { id: 'm-la-1', answer: "The resulting vector is <5, 7>", description: "Vector v1=<2,3> was added to vector v2=<3,4>. Explain component-wise vector addition.", difficulty: 'Easy' },
            { id: 'm-la-2', answer: "The dot product is 18", description: "This is the dot product of vectors v1=<2,4> and v2=<3,3>. Explain the calculation.", difficulty: 'Easy' },
            { id: 'm-la-3', answer: "The resulting vector is <8, 12>", description: "Vector v=<2,3> was multiplied by a scalar of 4. Explain scalar multiplication.", difficulty: 'Easy' },
            { id: 'm-la-4', answer: "The magnitude is 5", description: "This is the magnitude (or norm) of the vector v=<3,4>. Explain the formula, relating it to the Pythagorean theorem.", difficulty: 'Easy' },
            { id: 'm-la-5', answer: "The vectors are orthogonal.", description: "The dot product of two non-zero vectors was found to be 0. What does this imply about their geometric relationship?", difficulty: 'Medium' },
            { id: 'm-la-6', answer: "The resulting matrix is [[4, 6], [8, 10]]", description: "The matrix [[2, 3], [4, 5]] was multiplied by a scalar of 2. Explain how scalar multiplication applies to matrices.", difficulty: 'Easy' },
            { id: 'm-la-7', answer: "The resulting matrix is [[5, 7], [9, 11]]", description: "The matrices [[1, 2], [3, 4]] and [[4, 5], [6, 7]] were added together. Explain matrix addition.", difficulty: 'Easy' },
            { id: 'm-la-8', answer: "The determinant is -2", description: "This is the determinant of the 2x2 matrix [[1, 2], [3, 4]]. Explain the formula ad-bc.", difficulty: 'Medium' },
            { id: 'm-la-9', answer: "The matrix is singular.", description: "The determinant of a square matrix was calculated to be 0. What does this mean for its invertibility?", difficulty: 'Medium' },
            { id: 'm-la-10', answer: "The solution is x=2, y=1", description: "This is the solution to the system of linear equations: 2x + 3y = 7 and x - y = 1. Explain how this system can be represented in matrix form (Ax=b).", difficulty: 'Medium' },
            { id: 'm-la-11', answer: "The resulting matrix is [[19, 22], [43, 50]]", description: "The matrix [[1, 2], [3, 4]] was multiplied by [[5, 6], [7, 8]]. Explain the process of matrix multiplication.", difficulty: 'Hard' },
            { id: 'm-la-12', answer: "The dimension of the null space is 1.", description: "A 3x3 matrix was found to have a rank of 2. Explain the rank-nullity theorem.", difficulty: 'Hard' },
            { id: 'm-la-13', answer: "The eigenvalue is 5", description: "For a matrix A and a vector v, it was found that Av = 5v. Define what an eigenvalue and eigenvector are in this context.", difficulty: 'Hard' },
            { id: 'm-la-14', answer: "The set of vectors is linearly dependent.", description: "One vector in a set of three 2D vectors could be written as a linear combination of the other two. What does this mean?", difficulty: 'Medium' },
            { id: 'm-la-15', answer: "The matrix is an identity matrix.", description: "A square matrix has 1s on the main diagonal and 0s everywhere else. What is its special name and property in multiplication?", difficulty: 'Easy' },
            { id: 'm-la-16', answer: "The resulting matrix is [[1, 3], [2, 4]]", description: "The matrix [[1, 2], [3, 4]] was transposed. Explain the process of transposing a matrix.", difficulty: 'Easy' },
            { id: 'm-la-17', answer: "The inverse matrix is [[-2, 1], [1.5, -0.5]]", description: "This is the inverse of the matrix [[1, 2], [3, 4]]. Explain the formula for finding the inverse of a 2x2 matrix.", difficulty: 'Hard' },
            { id: 'm-la-18', answer: "The transformation rotates vectors by 90 degrees counter-clockwise.", description: "A vector <x, y> was transformed by the matrix [[0, -1], [1, 0]] to become <-y, x>. Describe this linear transformation geometrically.", difficulty: 'Hard' },
            { id: 'm-la-19', answer: "The vectors form a basis for R^2.", description: "Two vectors in R^2 were found to be linearly independent. Explain why they must span the entire 2D space.", difficulty: 'Medium' },
            { id: 'm-la-20', answer: "The cross product is <-3, 6, -3>", description: "This is the cross product of vectors <2, 1, 1> and <1, 2, 1>. Explain what the cross product represents geometrically and how to compute it.", difficulty: 'Hard' }
        ]
    },
    {
        id: 'm-topic-prob-stats', name: 'Probability & Statistics', description: 'Quantifying uncertainty and deriving insights from data.',
        challenges: [
            { id: 'm-ps-1', answer: "The mean is 5.", description: "The data set was {2, 4, 6, 8}. Explain how to calculate the arithmetic mean.", difficulty: 'Easy' },
            { id: 'm-ps-2', answer: "The median is 5.5.", description: "The data set was {2, 4, 7, 9}. Explain how to find the median of an even-sized set.", difficulty: 'Easy' },
            { id: 'm-ps-3', answer: "The probability is 1/6.", description: "A fair six-sided die was rolled once. This was the probability of rolling a 4. Explain basic probability.", difficulty: 'Easy' },
            { id: 'm-ps-4', answer: "The mode is 7.", description: "The data set was {3, 5, 7, 7, 8, 9}. Explain what the mode of a data set represents.", difficulty: 'Easy' },
            { id: 'm-ps-5', answer: "The probability is 1/2.", description: "A fair coin was tossed. This was the probability of getting heads. Explain the concept of sample space.", difficulty: 'Easy' },
            { id: 'm-ps-6', answer: "The range is 10.", description: "The data set was {2, 5, 8, 12}. Explain how to calculate the range.", difficulty: 'Easy' },
            { id: 'm-ps-7', answer: "The probability is 1/4.", description: "Two fair coins were tossed. This was the probability of getting two heads. Explain the multiplication rule for independent events.", difficulty: 'Medium' },
            { id: 'm-ps-8', answer: "The standard deviation is approximately 2.23.", description: "The variance of a data set was calculated to be 5. How is the standard deviation derived from the variance?", difficulty: 'Medium' },
            { id: 'm-ps-9', answer: "This is a Type I error.", description: "In hypothesis testing, a true null hypothesis was rejected. Define this type of error.", difficulty: 'Hard' },
            { id: 'm-ps-10', answer: "The events are dependent.", description: "The probability of drawing a second King from a deck of cards, given that the first card drawn was a King and not replaced. Explain why these events are dependent.", difficulty: 'Medium' },
            { id: 'm-ps-11', answer: "There are 24 possible arrangements.", description: "This is the number of ways to arrange 4 different books on a shelf. Explain the concept of factorial (4!).", difficulty: 'Medium' },
            { id: 'm-ps-12', answer: "The probability is 2/52 (or 1/26).", description: "This is the probability of drawing a black king from a standard 52-card deck. Explain the calculation.", difficulty: 'Easy' },
            { id: 'm-ps-13', answer: "The p-value is 0.03.", description: "In a statistical test, this value was found. Since it was less than the significance level of 0.05, the null hypothesis was rejected. Explain the role of the p-value.", difficulty: 'Hard' },
            { id: 'm-ps-14', answer: "The correlation coefficient is -0.9.", description: "This value was calculated for two variables. Describe the strength and direction of the linear relationship.", difficulty: 'Medium' },
            { id: 'm-ps-15', answer: "The result is 10.", description: "This is the number of combinations of choosing 2 items from a set of 5 (5C2). Explain the combination formula.", difficulty: 'Medium' },
            { id: 'm-ps-16', answer: "This is a normal distribution.", description: "A probability distribution is symmetric, bell-shaped, and defined by its mean and standard deviation. Identify this distribution.", difficulty: 'Easy' },
            { id: 'm-ps-17', answer: "The conditional probability is 1/3.", description: "Given that a roll of a fair die is an odd number, this is the probability that it is a 3. Explain Bayes' theorem or the conditional probability formula P(A|B).", difficulty: 'Hard' },
        ]
    },
    {
        id: 'm-topic-trig', name: 'Trigonometry', description: 'The relationships between angles and side lengths of triangles.',
        challenges: [
            { id: 'm-trig-1', answer: "The value is 1.", description: "This is the result of sin²(θ) + cos²(θ). Identify this fundamental trigonometric identity.", difficulty: 'Easy' },
            { id: 'm-trig-2', answer: "The value is 0.5.", description: "This is the value of sin(30°).", difficulty: 'Easy' },
            { id: 'm-trig-3', answer: "The value is approximately 0.866.", description: "This is the value of cos(30°).", difficulty: 'Easy' },
            { id: 'm-trig-4', answer: "The value is 1.", description: "This is the value of tan(45°).", difficulty: 'Easy' },
            { id: 'm-trig-5', answer: "The hypotenuse is 5.", description: "In a right-angled triangle, the other two sides are 3 and 4. Explain how the Pythagorean theorem is used.", difficulty: 'Easy' },
            { id: 'm-trig-6', answer: "The answer is Quadrant II.", description: "For an angle θ, sin(θ) is positive and cos(θ) is negative. In which quadrant does θ lie?", difficulty: 'Medium' },
            { id: 'm-trig-7', answer: "The value is csc(θ).", description: "This is the reciprocal of sin(θ).", difficulty: 'Easy' },
            { id: 'm-trig-8', answer: "The period is 2π.", description: "This is the period of the function f(x) = sin(x). Explain what the period of a function means.", difficulty: 'Medium' },
            { id: 'm-trig-9', answer: "The value is 4/5.", description: "In a right triangle, the side opposite angle θ is 4 and the hypotenuse is 5. What is sin(θ)?", difficulty: 'Easy' },
            { id: 'm-trig-10', answer: "The law of sines was used.", description: "In a non-right triangle, a side length was found using the ratio of the side to the sine of its opposite angle. Identify the law used.", difficulty: 'Medium' },
            { id: 'm-trig-11', answer: "The value is cos(2θ).", description: "This is the result of cos²(θ) - sin²(θ). Identify this double angle identity.", difficulty: 'Hard' },
            { id: 'm-trig-12', answer: "The amplitude is 3.", description: "This is the amplitude of the function f(x) = 3cos(x). Explain what amplitude represents.", difficulty: 'Easy' },
        ]
    },
];

const PHYSICS_TOPICS: Topic[] = [
    {
        id: 'p-topic-newtonian', name: 'Newtonian Mechanics', description: 'The fundamental laws governing motion and force.',
        challenges: [
            { id: 'p-nm-1', answer: "The net force is 50 N.", description: "A 10 kg object is accelerating at 5 m/s². Explain how Newton's Second Law (F=ma) is used to find the force.", difficulty: 'Easy' },
            { id: 'p-nm-2', answer: "The final velocity is 20 m/s.", description: "An object starts from rest and accelerates at 2 m/s² for 10 seconds. Explain the kinematic equation used.", difficulty: 'Easy' },
            { id: 'p-nm-3', answer: "The momentum is 30 kg·m/s.", description: "A 3 kg object is moving at 10 m/s. Explain the formula for momentum (p=mv).", difficulty: 'Easy' },
            { id: 'p-nm-4', answer: "The gravitational potential energy is 196 J.", description: "A 10 kg mass is held 2 meters above the ground (g ≈ 9.8 m/s²). Explain the formula for GPE.", difficulty: 'Easy' },
            { id: 'p-nm-5', answer: "The kinetic energy is 50 J.", description: "A 4 kg object is moving at 5 m/s. Explain the formula for kinetic energy (KE = 1/2 * mv²).", difficulty: 'Easy' },
            { id: 'p-nm-6', answer: "The work done is 100 J.", description: "A force of 20 N is applied to an object, moving it 5 meters in the same direction. Explain the formula for work (W = Fd).", difficulty: 'Easy' },
            { id: 'p-nm-7', answer: "The tension in the rope is 98 N.", description: "A 10 kg mass hangs motionless from a rope. Explain Newton's First Law and the concept of equilibrium.", difficulty: 'Medium' },
            { id: 'p-nm-8', answer: "The final velocity is 4 m/s.", description: "A 2kg cart moving at 6 m/s collides and sticks to a stationary 1kg cart. Explain the conservation of momentum for this inelastic collision.", difficulty: 'Medium' },
            { id: 'p-nm-9', answer: "The period of the pendulum is approximately 2.0 seconds.", description: "A simple pendulum has a length of 1 meter. Explain the formula for the period of a simple pendulum.", difficulty: 'Medium' },
            { id: 'p-nm-10', answer: "The centripetal acceleration is 8 m/s².", description: "An object moves in a circle of radius 2m at a constant speed of 4 m/s. Explain the formula for centripetal acceleration (a = v²/r).", difficulty: 'Medium' },
            { id: 'p-nm-11', answer: "The block will slide.", description: "The coefficient of static friction between a 5kg block and a surface is 0.4. A horizontal force of 25 N is applied (g ≈ 9.8 m/s²). Explain how to compare the applied force to the maximum static friction force.", difficulty: 'Hard' },
            { id: 'p-nm-12', answer: "The bullet's initial speed was 400 m/s.", description: "A 10g bullet is fired into a stationary 1.99kg block of wood, which then slides at 2 m/s. Explain conservation of momentum.", difficulty: 'Hard' },
            { id: 'p-nm-13', answer: "The maximum height is 20.4 m.", description: "A ball is thrown straight up with an initial velocity of 20 m/s. Explain how to use conservation of energy or kinematics to find its peak height.", difficulty: 'Medium' },
            { id: 'p-nm-14', answer: "The angular momentum is 40 kg·m²/s.", description: "A point mass of 2 kg is rotating at a radius of 2 m with a tangential velocity of 10 m/s. Explain the formula for angular momentum (L = mvr).", difficulty: 'Hard' },
            { id: 'p-nm-15', answer: "The torque is 10 N·m.", description: "A force of 20 N is applied perpendicularly to a wrench at a distance of 0.5 m from the pivot. Explain the formula for torque (τ = rF).", difficulty: 'Easy' },
            { id: 'p-nm-16', answer: "The gravitational force is 1.99 x 10^20 N.", description: "This is the approximate gravitational force between the Earth and the Moon. Explain Newton's Law of Universal Gravitation.", difficulty: 'Hard' },
            { id: 'p-nm-17', answer: "The coefficient of kinetic friction is 0.2.", description: "A 10 N force is required to keep a 5 kg block moving at a constant velocity across a horizontal surface. Explain how to find the friction force and the coefficient.", difficulty: 'Medium' },
            { id: 'p-nm-18', answer: "The object lands 40.8 m away.", description: "An object is launched at 20 m/s at an angle of 30 degrees from the ground. Explain how to calculate the range of a projectile.", difficulty: 'Hard' },
            { id: 'p-nm-19', answer: "The spring constant is 200 N/m.", description: "A spring stretches by 0.1 m when a 20 N force is applied. Explain Hooke's Law (F = kx).", difficulty: 'Easy' },
            { id: 'p-nm-20', answer: "The power exerted is 40 W.", description: "A person pushes a box with a force of 20 N, keeping it moving at a constant velocity of 2 m/s. Explain the formula for power (P = Fv).", difficulty: 'Medium' }
        ]
    },
    {
        id: 'p-topic-em', name: 'Electromagnetism', description: 'The interplay of electric and magnetic fields.',
        challenges: [
            { id: 'p-em-1', answer: "The current is 2 A.", description: "A 6-ohm resistor is connected to a 12-volt battery. Explain how Ohm's Law (V=IR) is used.", difficulty: 'Easy' },
            { id: 'p-em-2', answer: "The equivalent resistance is 10 Ω.", description: "Two resistors, 4 Ω and 6 Ω, are connected in series. Explain how to find the total resistance.", difficulty: 'Easy' },
            { id: 'p-em-3', answer: "The force is 90 N.", description: "Two point charges, +2 C and -3 C, are separated by 1 meter in a vacuum. The resulting force has a magnitude of ~5.4x10^10 N. Explain Coulomb's Law. Wait, that's too big. A different scenario resulted in 90N.", difficulty: 'Medium' },
            { id: 'p-em-4', answer: "The equivalent resistance is 2.4 Ω.", description: "Two resistors, 4 Ω and 6 Ω, are connected in parallel. Explain the formula for parallel resistance.", difficulty: 'Medium' },
            { id: 'p-em-5', answer: "The magnetic field points out of the page.", description: "A wire carries a current flowing to the right. Explain the right-hand rule for determining the direction of the magnetic field above the wire.", difficulty: 'Medium' },
            { id: 'p-em-6', answer: "The power dissipated is 24 W.", description: "A 12V source is connected to a 6Ω resistor. Explain the formula for power (P = V²/R or P = I²R).", difficulty: 'Easy' },
            { id: 'p-em-7', answer: "The capacitance is 5 F.", description: "A capacitor stores 20 Coulombs of charge when connected to a 4-volt battery. Explain the formula for capacitance (Q=CV).", difficulty: 'Easy' },
            { id: 'p-em-8', answer: "The magnetic force is 0.6 N.", description: "A 2m wire carrying 3A of current is in a perpendicular magnetic field of 0.1 T. Explain the formula for the force on a current-carrying wire (F = ILB).", difficulty: 'Medium' },
            { id: 'p-em-9', answer: "An EMF of 2V is induced.", description: "The magnetic flux through a coil of wire changes by 10 Wb in 5 seconds. Explain Faraday's Law of Induction.", difficulty: 'Hard' },
            { id: 'p-em-10', answer: "The direction of the induced current creates a North pole to oppose the change.", description: "The North pole of a magnet is moved towards a loop of wire. Explain Lenz's Law.", difficulty: 'Hard' },
        ]
    },
    {
        id: 'p-topic-thermo', name: 'Thermodynamics', description: 'The behavior of heat, energy, and entropy.',
        challenges: [
            { id: 'p-th-1', answer: "The final temperature is 30°C.", description: "1 kg of water at 20°C is mixed with 1 kg of water at 40°C. Assuming no heat loss, explain the principle of thermal equilibrium.", difficulty: 'Easy' },
            { id: 'p-th-2', answer: "The process is Isothermal.", description: "A gas expands while its temperature is held constant. Identify this thermodynamic process.", difficulty: 'Medium' },
            { id: 'p-th-3', answer: "The pressure is 2 atm.", description: "An ideal gas in a 10L container at a certain temperature and mole count has its volume halved to 5L while keeping temperature constant. Explain Boyle's Law (P₁V₁=P₂V₂).", difficulty: 'Easy' },
            { id: 'p-th-4', answer: "Heat is transferred via convection.", description: "Boiling water circulates, transferring heat throughout the pot. Identify this mode of heat transfer.", difficulty: 'Easy' },
            { id: 'p-th-5', answer: "This violates the Second Law of Thermodynamics.", description: "A machine was designed to take heat from a cold reservoir and move it to a hot reservoir without any work input. Explain why this is impossible.", difficulty: 'Hard' },
            { id: 'p-th-6', answer: "The change in internal energy is 70 J.", description: "100 J of heat is added to a system, and the system does 30 J of work on its surroundings. Explain the First Law of Thermodynamics (ΔU = Q - W).", difficulty: 'Medium' },
        ]
    },
    {
        id: 'p-topic-quantum', name: 'Quantum Mechanics', description: 'The strange and wonderful rules of the subatomic world.',
        challenges: [
            { id: 'p-qm-1', answer: "The phenomenon is the Photoelectric Effect.", description: "Light shining on a metal surface caused electrons to be ejected, but only if the light's frequency was above a certain threshold. Identify this key quantum phenomenon.", difficulty: 'Medium' },
            { id: 'p-qm-2', answer: "The particle's position is highly uncertain.", description: "The momentum of a quantum particle was measured with very high precision. According to the Heisenberg Uncertainty Principle, what does this imply about the uncertainty of its position?", difficulty: 'Hard' },
            { id: 'p-qm-3', answer: "The De Broglie wavelength is 2.2 x 10⁻¹¹ m.", description: "An electron is moving at 3 x 10⁷ m/s. Explain how to calculate its matter-wave wavelength.", difficulty: 'Hard' },
            { id: 'p-qm-4', answer: "This describes wave-particle duality.", description: "An electron was observed to behave as a wave when not being measured, but as a particle when a measurement was made. What is this fundamental concept of quantum mechanics?", difficulty: 'Medium' },
            { id: 'p-qm-5', answer: "This represents quantized energy levels.", description: "An electron in an atom can only exist in specific, discrete energy states, and not in between. What is this concept called?", difficulty: 'Medium' },
        ]
    },
];

const CHEMISTRY_TOPICS: Topic[] = [
    {
        id: 'c-topic-stoichiometry', name: 'Stoichiometry', description: 'The quantitative relationships in chemical reactions.',
        challenges: [
            { id: 'c-s-1', answer: "The molar mass is 44.01 g/mol.", description: "This is the molar mass of carbon dioxide (CO₂). Explain how to calculate it using atomic masses from the periodic table.", difficulty: 'Easy' },
            { id: 'c-s-2', answer: "There are 2 moles of water.", description: "A sample of 36.04 grams of water (H₂O) was measured. Explain the conversion from grams to moles.", difficulty: 'Easy' },
            { id: 'c-s-3', answer: "The product is 88.02 g of CO₂.", description: "The complete combustion of 24 g of carbon with excess oxygen produces CO₂. Explain the balanced equation and stoichiometric calculation.", difficulty: 'Medium' },
            { id: 'c-s-4', answer: "The limiting reactant is O₂.", description: "A reaction uses 2 moles of H₂ and 0.5 moles of O₂ to produce H₂O. Based on the balanced equation 2H₂ + O₂ -> 2H₂O, explain why oxygen is the limiting reactant.", difficulty: 'Medium' },
            { id: 'c-s-5', answer: "The percent yield is 80%.", description: "A reaction was theoretically supposed to produce 50g of a substance, but the actual experiment only yielded 40g. Explain how percent yield is calculated.", difficulty: 'Easy' },
            { id: 'c-s-6', answer: "The empirical formula is CH₂O.", description: "A compound was found to be 40% Carbon, 6.7% Hydrogen, and 53.3% Oxygen by mass. Explain the steps to determine its empirical formula.", difficulty: 'Hard' },
            { id: 'c-s-7', answer: "The molecular formula is C₆H₁₂O₆.", description: "A compound with an empirical formula of CH₂O was found to have a molar mass of 180.16 g/mol. Explain how to determine its molecular formula.", difficulty: 'Hard' },
            { id: 'c-s-8', answer: "The molarity is 2 M.", description: "A solution was prepared by dissolving 2 moles of NaCl in enough water to make 1 liter of solution. Explain the definition of molarity.", difficulty: 'Easy' },
            { id: 'c-s-9', answer: "5.4 grams of Al were used.", description: "A reaction between aluminum (Al) and excess copper chloride produced 19.05 g of copper (Cu), according to 2Al + 3CuCl₂ -> 2AlCl₃ + 3Cu. Explain the mole-to-mole and mole-to-gram conversions needed.", difficulty: 'Hard' },
            { id: 'c-s-10', answer: "50 mL of stock solution was needed.", description: "A 0.5 M solution was created by diluting a 2.0 M stock solution to a final volume of 200 mL. Explain the dilution equation M₁V₁ = M₂V₂.", difficulty: 'Medium' },
            { id: 'c-s-11', answer: 'The balanced coefficient is 2.', description: 'In the combustion of methane (CH₄ + O₂ -> CO₂ + H₂O), what is the coefficient for O₂?', difficulty: 'Easy' },
            { id: 'c-s-12', answer: 'The concentration is 0.5 mol/L.', description: '49g of sulfuric acid (H₂SO₄, molar mass 98 g/mol) is dissolved in 1L of water. Explain the calculation for molarity.', difficulty: 'Medium' },
            { id: 'c-s-13', answer: '1.204 x 10^24 atoms.', description: 'This is the number of atoms in 2 moles of helium. Explain the role of Avogadro\'s number.', difficulty: 'Easy' },
            { id: 'c-s-14', answer: 'The mass of oxygen is 32g.', description: 'In the reaction 2Mg + O₂ -> 2MgO, 48.6g of Mg reacts completely. Explain how to find the mass of O₂ needed.', difficulty: 'Medium' },
            { id: 'c-s-15', answer: 'A precipitate of AgCl forms.', description: 'Aqueous solutions of AgNO₃ and NaCl are mixed. Explain what type of reaction occurs and identify the solid product.', difficulty: 'Medium' },
            { id: 'c-s-16', answer: 'The volume of gas is 22.4 L.', description: 'This is the volume occupied by 1 mole of any ideal gas at Standard Temperature and Pressure (STP). What is this principle called?', difficulty: 'Easy' },
            { id: 'c-s-17', answer: 'The reaction produced 1.5 moles of N₂.', description: 'The decomposition of 1 mole of sodium azide (NaN₃) follows 2NaN₃ -> 2Na + 3N₂. Explain the mole ratio.', difficulty: 'Medium' },
            { id: 'c-s-18', answer: 'The mass percentage of C in CO₂ is 27.29%.', description: 'The molar mass of C is 12.01 g/mol and CO₂ is 44.01 g/mol. Explain the calculation for mass percent.', difficulty: 'Easy' },
            { id: 'c-s-19', answer: '2 moles of HCl are left over.', description: '5 moles of HCl react with 1.5 moles of Mg (Mg + 2HCl -> MgCl₂ + H₂). Explain how to find the amount of excess reactant remaining.', difficulty: 'Hard' },
            { id: 'c-s-20', answer: 'The titration required 25 mL of base.', description: 'A 25 mL sample of 0.1 M HCl was neutralized by 0.1 M NaOH. Explain why the volumes are equal in this 1:1 acid-base titration.', difficulty: 'Medium' }
        ]
    },
    {
        id: 'c-topic-org1', name: 'Organic Chemistry I', description: 'Introduction to carbon-based compounds, alkanes, and alkenes.',
        challenges: [
            { id: 'c-o1-1', answer: "The molecule is an alkane.", description: "A hydrocarbon contains only single bonds. What class of compound is it?", difficulty: 'Easy' },
            { id: 'c-o1-2', answer: "The name is 2-methylpentane.", description: "This is the IUPAC name for an isomer of hexane with a branched structure. Draw it and explain the naming rules.", difficulty: 'Medium' },
            { id: 'c-o1-3', answer: "The structure has cis-trans isomers.", description: "A molecule of 2-butene was considered. Explain why this molecule exhibits geometric isomerism.", difficulty: 'Hard' },
            { id: 'c-o1-4', answer: "The product is 2-bromopropane.", description: "Propene reacts with HBr. Explain Markovnikov's rule in determining the major product.", difficulty: 'Medium' },
            { id: 'c-o1-5', answer: "The compound is cyclohexane.", description: "A cyclic alkane with the formula C₆H₁₂. What is its name?", difficulty: 'Easy' },
        ]
    },
    {
        id: 'c-topic-acid-base', name: 'Acids & Bases', description: 'The properties of acidic and basic solutions.',
        challenges: [
            { id: 'c-ab-1', answer: "The pH is 3.", description: "A solution has a hydrogen ion concentration of [H+] = 1 x 10⁻³ M. Explain the formula for pH.", difficulty: 'Easy' },
            { id: 'c-ab-2', answer: "The solution is acidic.", description: "A solution has a pH of 5. Is it acidic, basic, or neutral? Explain the pH scale.", difficulty: 'Easy' },
            { id: 'c-ab-3', answer: "The products are a salt and water.", description: "A strong acid reacts with a strong base. What are the general products of this neutralization reaction?", difficulty: 'Easy' },
            { id: 'c-ab-4', answer: "The conjugate base is Cl⁻.", description: "When hydrochloric acid (HCl) donates a proton, what species remains? Define a conjugate base.", difficulty: 'Medium' },
            { id: 'c-ab-5', answer: "It is a buffer solution.", description: "A solution contains a weak acid and its conjugate base, and it resists changes in pH. What is this type of solution called?", difficulty: 'Medium' },
        ]
    },
];

const CS_TOPICS: Topic[] = [
    {
        id: 'cs-topic-algo', name: 'Algorithms & Complexity', description: 'The efficiency and structure of computational procedures.',
        challenges: [
            { id: 'cs-ac-1', answer: "The time complexity is O(n²).", description: "An algorithm with a nested loop, where both loops run 'n' times, was analyzed. Explain why this leads to quadratic time complexity.", difficulty: 'Easy' },
            { id: 'cs-ac-2', answer: "The time complexity is O(log n).", description: "A binary search algorithm was used on a sorted array of 'n' elements. Explain why its time complexity is logarithmic.", difficulty: 'Medium' },
            { id: 'cs-ac-3', answer: "The time complexity is O(1).", description: "An algorithm accessed an element in an array by its index. Explain why this is a constant time operation.", difficulty: 'Easy' },
            { id: 'cs-ac-4', answer: "The algorithm is Bubble Sort.", description: "An array was sorted by repeatedly swapping adjacent elements if they were in the wrong order. Identify this simple (but inefficient) sorting algorithm.", difficulty: 'Easy' },
            { id: 'cs-ac-5', answer: "The algorithm is Merge Sort.", description: "An array was sorted by recursively dividing it in half, sorting the halves, and then merging them back together. Identify this efficient, divide-and-conquer algorithm.", difficulty: 'Medium' },
            { id: 'cs-ac-6', answer: "The output is 55.", description: "A function was called to find the 10th number in the Fibonacci sequence. Explain the recursive definition F(n) = F(n-1) + F(n-2).", difficulty: 'Medium' },
            { id: 'cs-ac-7', answer: "A greedy algorithm was used.", description: "To solve a problem of giving change, a program always chose the largest possible coin denomination first. Name this algorithmic paradigm.", difficulty: 'Medium' },
            { id: 'cs-ac-8', answer: "The space complexity is O(n).", description: "An algorithm created a copy of an input array of size 'n'. Explain why this results in linear space complexity.", difficulty: 'Easy' },
            { id: 'cs-ac-9', answer: "The algorithm is Dijkstra's Algorithm.", description: "The shortest path from a single source node to all other nodes in a weighted graph was found. Identify this classic graph algorithm.", difficulty: 'Hard' },
            { id: 'cs-ac-10', answer: "The time complexity is O(n).", description: "An algorithm iterated through an array of 'n' elements once to find the maximum value. Explain why this is a linear time operation.", difficulty: 'Easy' },
            { id: 'cs-ac-11', answer: 'The result is 24.', description: 'The factorial of 4 was computed. Explain the recursive logic n * factorial(n-1).', difficulty: 'Easy' },
            { id: 'cs-ac-12', answer: 'A linear search was performed.', description: 'An algorithm checked every element of an unsorted array sequentially to find a value. Identify this search method.', difficulty: 'Easy' },
            { id: 'cs-ac-13', answer: 'The time complexity is O(n log n).', description: 'An optimal comparison-based sorting algorithm like Quicksort (average case) or Heapsort was used. What is its typical time complexity?', difficulty: 'Medium' },
            { id: 'cs-ac-14', answer: 'This is a Dynamic Programming approach.', description: 'An algorithm solved a problem by breaking it down into simpler subproblems and storing the results of subproblems to avoid re-computation (memoization). Name this paradigm.', difficulty: 'Hard' },
            { id: 'cs-ac-15', answer: 'The best case is O(1).', description: 'In a linear search of \'n\' items, the target value was the very first element. What is the best-case time complexity?', difficulty: 'Easy' },
            { id: 'cs-ac-16', answer: 'The space complexity is O(log n).', description: 'For a recursive binary search, the call stack depth is proportional to the logarithm of the input size. Explain this space complexity.', difficulty: 'Hard' },
            { id: 'cs-ac-17', answer: 'The algorithm is Selection Sort.', description: 'An array was sorted by repeatedly finding the minimum element from the unsorted part and putting it at the beginning. Identify this algorithm.', difficulty: 'Medium' },
            { id: 'cs-ac-18', answer: 'A Breadth-First Search (BFS) was used.', description: 'An algorithm explored a graph level by level from a starting node, using a queue. Identify this graph traversal algorithm.', difficulty: 'Medium' },
            { id: 'cs-ac-19', answer: 'The worst case is O(n²).', description: 'The Quicksort algorithm was used on an already sorted array with a poor pivot selection strategy. What is its worst-case time complexity?', difficulty: 'Hard' },
            { id: 'cs-ac-20', answer: 'A Depth-First Search (DFS) was used.', description: 'An algorithm explored a-graph by going as deep as possible down one branch before backtracking, using a stack (often implicitly via recursion). Identify this algorithm.', difficulty: 'Medium' }
        ]
    },
    {
        id: 'cs-topic-data-struct', name: 'Data Structures', description: 'Organizing, managing, and storing data effectively.',
        challenges: [
            { id: 'cs-ds-1', answer: "The value 'D' was popped.", description: "A stack initially held ['A', 'B', 'C']. A 'D' was pushed. Finally, one value was popped. Explain the LIFO (Last-In, First-Out) principle.", difficulty: 'Easy' },
            { id: 'cs-ds-2', answer: "The value 'A' was dequeued.", description: "A queue initially held ['A', 'B', 'C']. A 'D' was enqueued. Finally, one value was dequeued. Explain the FIFO (First-In, First-Out) principle.", difficulty: 'Easy' },
            { id: 'cs-ds-3', answer: "The data structure is a Linked List.", description: "A collection of data elements (nodes) where each node points to the next, allowing for efficient insertion/deletion but slow random access. Identify this structure.", difficulty: 'Easy' },
            { id: 'cs-ds-4', answer: "The data structure is a Hash Table (or Map/Dictionary).", description: "A structure that maps keys to values for highly efficient lookups, often with O(1) average time complexity. Identify this structure.", difficulty: 'Medium' },
            { id: 'cs-ds-5', answer: "The data structure is a Binary Search Tree (BST).", description: "A tree where for each node, all values in its left subtree are smaller, and all values in its right subtree are larger. Identify this structure.", difficulty: 'Medium' },
            { id: 'cs-ds-6', answer: "The new array is [10, 20, 50, 30, 40].", description: "The value 50 was inserted at index 2 of the array [10, 20, 30, 40]. Explain why this can be an O(n) operation.", difficulty: 'Easy' },
            { id: 'cs-ds-7', answer: "A hash collision occurred.", description: "In a hash table, two different keys were mapped to the same index. What is this event called?", difficulty: 'Medium' },
            { id: 'cs-ds-8', answer: "The tree is a balanced binary search tree.", description: "A BST was modified to ensure its height remains O(log n) after insertions and deletions, preventing worst-case scenarios. Describe this type of tree (e.g., AVL, Red-Black).", difficulty: 'Hard' },
            { id: 'cs-ds-9', answer: "The traversal was 'in-order'.", description: "A traversal of a BST visited the nodes in sorted order (left, root, right). Identify this traversal type.", difficulty: 'Medium' },
            { id: 'cs-ds-10', answer: "The data structure is a Graph.", description: "A collection of nodes (vertices) connected by edges, used to model networks. Identify this non-linear data structure.", difficulty: 'Easy' },
            { id: 'cs-ds-11', answer: 'The root of the tree is 25.', description: 'In a BST, values 15, 30, 10, 20 were inserted after the initial root of 25. Explain why 25 remains the root.', difficulty: 'Easy' },
            { id: 'cs-ds-12', answer: 'The adjacency list is {A:[B,C], B:[A], C:[A]}.', description: 'A graph has nodes A, B, C with edges connecting A-B and A-C. Represent this using an adjacency list.', difficulty: 'Medium' },
            { id: 'cs-ds-13', answer: 'The data structure is a Heap.', description: 'A specialized tree-based structure satisfying the property that if P is a parent node of C, then the key of P is greater than or equal to the key of C (max-heap). Identify this structure, often used for priority queues.', difficulty: 'Hard' },
            { id: 'cs-ds-14', answer: 'The traversal was \'pre-order\'.', description: 'A traversal of a tree visited the root first, then the left subtree, then the right subtree. Identify this traversal.', difficulty: 'Medium' },
            { id: 'cs-ds-15', answer: 'A circular queue was implemented.', description: 'When a queue implemented with an array reached the end, new elements were added to the beginning if space was available. Describe this implementation technique.', difficulty: 'Hard' },
            { id: 'cs-ds-16', answer: 'The data structure is an Array.', description: 'A collection of items stored at contiguous memory locations. What is this fundamental data structure?', difficulty: 'Easy' },
            { id: 'cs-ds-17', answer: 'The traversal was \'post-order\'.', description: 'A traversal of a tree visited the left subtree, then the right subtree, then the root. Identify this traversal, often used to delete nodes safely.', difficulty: 'Medium' },
            { id: 'cs-ds-18', answer: 'The operation is peeking.', description: 'An operation looked at the top element of a stack without removing it. What is this operation called?', difficulty: 'Easy' },
            { id: 'cs-ds-19', answer: 'The data structure is a Trie.', description: 'A tree-like structure used for storing a dynamic set of strings, often used for autocomplete features. Identify this structure.', difficulty: 'Hard' },
            { id: 'cs-ds-20', answer: 'The graph contains a cycle.', description: 'During a DFS traversal of a graph, a back edge to an already visited node in the current recursion stack was found. What does this indicate?', difficulty: 'Hard' }
        ]
    },
    {
        id: 'cs-topic-oop', name: 'Object-Oriented Programming',
        description: 'A programming paradigm based on the concept of "objects".',
        challenges: [
            { id: 'cs-oop-1', answer: 'This demonstrates Inheritance.', description: 'A `Dog` class was created that acquired all the properties and methods of an `Animal` class. What is this OOP principle?', difficulty: 'Easy' },
            { id: 'cs-oop-2', answer: 'This is Encapsulation.', description: 'An object bundled its data (attributes) and the methods that operate on the data, hiding the internal state from the outside. What is this concept?', difficulty: 'Medium' },
            { id: 'cs-oop-3', answer: 'This is Polymorphism.', description: 'A single function name `makeSound()` was used for objects of different classes (`Dog`, `Cat`), and each object responded differently. What principle does this illustrate?', difficulty: 'Medium' },
            { id: 'cs-oop-4', answer: 'The `Car` is an object (or instance).', description: 'From a `Vehicle` class (a blueprint), a specific `Car` with a color of "red" was created. What is the `Car` in this context?', difficulty: 'Easy' },
            { id: 'cs-oop-5', answer: 'This is Abstraction.', description: 'A `Car` object has a `start_engine` method. The user doesn\'t need to know how the engine works, only that the method starts it. What principle involves hiding complex reality while exposing only essential parts?', difficulty: 'Hard' },
        ]
    },
    {
        id: 'cs-topic-databases', name: 'Database Systems',
        description: 'Designing, using, and implementing database systems (SQL).',
        challenges: [
            { id: 'cs-db-1', answer: 'A SELECT statement was used.', description: 'To retrieve data from a `Users` table, a query was written beginning with `SELECT * FROM Users`. Identify the SQL statement type.', difficulty: 'Easy' },
            { id: 'cs-db-2', answer: 'A WHERE clause was added.', description: 'To get only users from "USA", the clause `WHERE Country = \'USA\'` was added to a SELECT query. What is the purpose of this clause?', difficulty: 'Easy' },
            { id: 'cs-db-3', answer: 'A JOIN clause was used.', description: 'To combine rows from a `Users` table and an `Orders` table based on a related `user_id` column, a specific clause was used. What is it?', difficulty: 'Medium' },
            { id: 'cs-db-4', answer: 'This is a Primary Key.', description: 'A column in a table named `user_id` uniquely identifies each record in that table. What is this column called?', difficulty: 'Easy' },
            { id: 'cs-db-5', answer: 'This is a Foreign Key.', description: 'The `user_id` column in the `Orders` table links to the `user_id` in the `Users` table. What is the key in the `Orders` table called?', difficulty: 'Medium' },
            { id: 'cs-db-6', answer: 'The result is normalization.', description: 'A database was organized to minimize data redundancy and improve data integrity, for example by splitting large tables into smaller, well-structured ones. What is this process called?', difficulty: 'Hard' },
        ]
    },
];

const BIOLOGY_TOPICS: Topic[] = [
    {
        id: 'b-topic-genetics', name: 'Genetics', description: 'The study of genes, genetic variation, and heredity.',
        challenges: [
            { id: 'b-g-1', answer: "The phenotype is 'purple flowers'.", description: "In pea plants, the purple flower allele (P) is dominant over the white flower allele (p). A plant has the genotype PP. Describe its physical appearance.", difficulty: 'Easy' },
            { id: 'b-g-2', answer: "The ratio is 3:1.", description: "Two heterozygous (Pp) pea plants were crossed. This is the expected phenotypic ratio of purple to white flowers in the offspring. Explain using a Punnett square.", difficulty: 'Medium' },
            { id: 'b-g-3', answer: "The process is transcription.", description: "Inside the nucleus, a segment of DNA was used as a template to create a messenger RNA (mRNA) molecule. Name this process.", difficulty: 'Medium' },
            { id: 'b-g-4', answer: "The process is translation.", description: "At the ribosome, the genetic code on an mRNA molecule was read to synthesize a protein. Name this process.", difficulty: 'Medium' },
            { id: 'b-g-5', answer: "The result is two identical daughter cells.", description: "A somatic cell underwent cell division to produce two cells genetically identical to the parent cell. What is this type of cell division called (e.g., Mitosis)?", difficulty: 'Easy' },
            { id: 'b-g-6', answer: "The structure is a double helix.", description: "DNA is composed of two strands that wind around each other. What is this characteristic shape called?", difficulty: 'Easy' },
            { id: 'b-g-7', answer: "The base is Uracil (U).", description: "In RNA, this nitrogenous base pairs with Adenine (A) instead of Thymine (T).", difficulty: 'Easy' },
            { id: 'b-g-8', answer: "The result is four unique haploid cells.", description: "A germline cell underwent a two-stage cell division process to produce gametes (sperm or egg cells). What is this process called (e.g., Meiosis)?", difficulty: 'Medium' },
            { id: 'b-g-9', answer: "The genotype is heterozygous.", description: "An organism has two different alleles for a particular gene (e.g., Pp). What is the term for this genotype?", difficulty: 'Easy' },
            { id: 'b-g-10', answer: "This is a frameshift mutation.", description: "A single nucleotide was deleted from a DNA sequence, causing the reading frame of codons to shift. What type of mutation is this?", difficulty: 'Hard' },
        ]
    }
];
const ECONOMICS_TOPICS: Topic[] = [
    {
        id: 'e-topic-macro', name: 'Macroeconomics', description: 'The study of the economy as a whole.',
        challenges: [
            { id: 'e-ma-1', answer: "The result is inflation.", description: "The general price level in an economy increased, reducing the purchasing power of money. What is this phenomenon called?", difficulty: 'Easy' },
            { id: 'e-ma-2', answer: "The value is the Gross Domestic Product (GDP).", description: "The total monetary value of all the finished goods and services produced within a country's borders in a specific time period was calculated. What is this key economic indicator?", difficulty: 'Easy' },
            { id: 'e-ma-3', answer: "This is monetary policy.", description: "A country's central bank adjusted interest rates to control the money supply and stabilize the economy. What type of policy is this?", difficulty: 'Medium' },
            { id: 'e-ma-4', answer: "This is fiscal policy.", description: "A government changed its spending levels and tax rates to influence the economy. What type of policy is this?", difficulty: 'Medium' },
            { id: 'e-ma-5', answer: "The result is an increase in quantity demanded.", description: "The price of a popular brand of shoes went down, and as a result, more people bought them. Explain this basic principle of the law of demand.", difficulty: 'Easy' },
            { id: 'e-ma-6', answer: "The market is in equilibrium.", description: "The quantity of a product that buyers are willing to purchase is exactly equal to the quantity that sellers are willing to sell. What is this state called?", difficulty: 'Medium' },
        ]
    }
];
const BUSINESS_STUDIES_TOPICS: Topic[] = [
    {
        id: 'bs-topic-marketing', name: 'Marketing Principles', description: 'The fundamentals of promoting and selling products or services.',
        challenges: [
            { id: 'bs-m-1', answer: "These are the 4 Ps of Marketing.", description: "A company's marketing strategy focused on its Product, Price, Place, and Promotion. What is this combination famously called?", difficulty: 'Easy' },
            { id: 'bs-m-2', answer: "This is a SWOT analysis.", description: "A business evaluated its internal Strengths and Weaknesses, and its external Opportunities and Threats. What is this strategic planning framework called?", difficulty: 'Medium' },
            { id: 'bs-m-3', answer: "This is market segmentation.", description: "A company divided a broad consumer market into sub-groups based on shared characteristics like age, gender, and lifestyle. What is this process called?", difficulty: 'Medium' },
            { id: 'bs-m-4', answer: "The asset is brand equity.", description: "A company's brand name is so well-regarded that it adds significant value to the company's products beyond their functional benefits. What is this intangible asset?", difficulty: 'Hard' },
        ]
    }
];
const ACCOUNTANCY_TOPICS: Topic[] = [
    {
        id: 'a-topic-financial', name: 'Financial Accounting', description: 'Recording, summarizing, and reporting of financial transactions.',
        challenges: [
            { id: 'a-fa-1', answer: "The equation is Assets = Liabilities + Equity.", description: "This fundamental equation is the basis for the double-entry accounting system and the balance sheet. What is it?", difficulty: 'Easy' },
            { id: 'a-fa-2', answer: "The report is a Balance Sheet.", description: "A financial statement that reports a company's assets, liabilities, and shareholder equity at a specific point in time. Identify this report.", difficulty: 'Easy' },
            { id: 'a-fa-3', answer: "The report is an Income Statement.", description: "A financial statement that shows a company's revenues and expenses over a specific period, resulting in a net income or loss. Identify this report.", difficulty: 'Easy' },
            { id: 'a-fa-4', answer: "The transaction is a debit.", description: "In double-entry bookkeeping, an entry was made on the left side of an account. What is this type of entry called?", difficulty: 'Easy' },
            { id: 'a-fa-5', answer: "The transaction is a credit.", description: "In double-entry bookkeeping, an entry was made on the right side of an account. What is this type of entry called?", difficulty: 'Easy' },
        ]
    }
];
const HISTORY_TOPICS: Topic[] = [
    {
        id: 'h-topic-world', name: 'World History', description: 'Significant events and developments across the globe.',
        challenges: [
            { id: 'h-wh-1', answer: "The event was the fall of the Western Roman Empire.", description: "This event in 476 AD is often used by historians to mark the end of antiquity and the beginning of the Middle Ages in Europe.", difficulty: 'Easy' },
            { id: 'h-wh-2', answer: "The period was the Renaissance.", description: "A period of great cultural, artistic, and scientific rebirth in Europe that began in Italy in the 14th century. What was this 'reawakening' called?", difficulty: 'Medium' },
            { id: 'h-wh-3', answer: "The conflict was World War I.", description: "This global conflict from 1914-1918 was triggered by the assassination of Archduke Franz Ferdinand and involved the Central Powers and the Allied Powers.", difficulty: 'Easy' },
            { id: 'h-wh-4', answer: "The empire was the Mongol Empire.", description: "Led by figures like Genghis Khan, this 13th-century empire was the largest contiguous land empire in history.", difficulty: 'Medium' },
            { id: 'h-wh-5', answer: "The revolution was the Industrial Revolution.", description: "Beginning in Great Britain in the late 18th century, this period saw a major shift from agrarian societies to industrial, urban ones.", difficulty: 'Easy' },
        ]
    }
];
const GEOGRAPHY_TOPICS: Topic[] = [
    {
        id: 'g-topic-physical', name: 'Physical Geography', description: 'The study of processes and patterns in the natural environment.',
        challenges: [
            { id: 'g-pg-1', answer: "The theory is Plate Tectonics.", description: "This scientific theory describes the large-scale motion of the Earth's lithosphere, explaining earthquakes and continental drift.", difficulty: 'Easy' },
            { id: 'g-pg-2', answer: "The process is the Water Cycle.", description: "This is the continuous movement of water on, above, and below the surface of the Earth, involving evaporation, condensation, and precipitation. Name the cycle.", difficulty: 'Easy' },
            { id: 'g-pg-3', answer: "The term is 'weather'.", description: "This term describes the state of the atmosphere at a particular place and time, including temperature, humidity, and wind. Is it weather or climate?", difficulty: 'Easy' },
            { id: 'g-pg-4', answer: "The line is the Equator.", description: "This imaginary line at 0 degrees latitude divides the Earth into the Northern and Southern Hemispheres.", difficulty: 'Easy' },
        ]
    }
];
const POLITICAL_SCIENCE_TOPICS: Topic[] = [
    {
        id: 'ps-topic-theory', name: 'Political Theory', description: 'The study of political ideas and values like justice, power and rights.',
        challenges: [
            { id: 'ps-pt-1', answer: "The system is a Democracy.", description: "A system of government where supreme power is vested in the people and exercised by them directly or indirectly through a system of representation. What is this system?", difficulty: 'Easy' },
            { id: 'ps-pt-2', answer: "The concept is 'separation of powers'.", description: "A model of governance where the state is divided into branches (e.g., legislative, executive, judicial), each with separate and independent powers. What is this principle?", difficulty: 'Medium' },
            { id: 'ps-pt-3', answer: "The philosopher was John Locke.", description: "This Enlightenment thinker argued for natural rights of 'life, liberty, and property' and heavily influenced the U.S. Declaration of Independence.", difficulty: 'Hard' },
            { id: 'ps-pt-4', answer: "The system is Communism.", description: "A political and economic ideology that positions itself in opposition to liberal democracy and capitalism, advocating for a classless system in which the means of production are owned communally.", difficulty: 'Medium' },
        ]
    }
];


export const SUBJECT_TOPICS: Record<Subject, Topic[]> = {
    Math: MATH_TOPICS,
    Physics: PHYSICS_TOPICS,
    Chemistry: CHEMISTRY_TOPICS,
    CS: CS_TOPICS,
    Biology: BIOLOGY_TOPICS,
    Economics: ECONOMICS_TOPICS,
    'Business Studies': BUSINESS_STUDIES_TOPICS,
    Accountancy: ACCOUNTANCY_TOPICS,
    History: HISTORY_TOPICS,
    Geography: GEOGRAPHY_TOPICS,
    'Political Science': POLITICAL_SCIENCE_TOPICS,
};

export const SUBJECTS_BY_STREAM: Record<Stream, Subject[]> = {
    'Non-Medical': ['Physics', 'Chemistry', 'Math', 'CS'],
    'Medical': ['Physics', 'Chemistry', 'Biology'],
    'Commerce': ['Accountancy', 'Business Studies', 'Economics', 'Math'],
    'Arts': ['History', 'Geography', 'Political Science', 'Economics'],
};

// A flattened version for Time Trials for simplicity
export const challengesBySubject: Record<Subject, Challenge[]> = {
    Math: SUBJECT_TOPICS.Math.flatMap(topic => topic.challenges),
    Physics: SUBJECT_TOPICS.Physics.flatMap(topic => topic.challenges),
    Chemistry: SUBJECT_TOPICS.Chemistry.flatMap(topic => topic.challenges),
    CS: SUBJECT_TOPICS.CS.flatMap(topic => topic.challenges),
    Biology: SUBJECT_TOPICS.Biology.flatMap(topic => topic.challenges),
    Economics: SUBJECT_TOPICS.Economics.flatMap(topic => topic.challenges),
    'Business Studies': SUBJECT_TOPICS['Business Studies'].flatMap(topic => topic.challenges),
    Accountancy: SUBJECT_TOPICS.Accountancy.flatMap(topic => topic.challenges),
    History: SUBJECT_TOPICS.History.flatMap(topic => topic.challenges),
    Geography: SUBJECT_TOPICS.Geography.flatMap(topic => topic.challenges),
    'Political Science': SUBJECT_TOPICS['Political Science'].flatMap(topic => topic.challenges),
};

export const subjectByChallengeId: Record<string, Subject> = {};
for (const subject in challengesBySubject) {
    if (Object.prototype.hasOwnProperty.call(challengesBySubject, subject as Subject)) {
        challengesBySubject[subject as Subject].forEach(challenge => {
            subjectByChallengeId[challenge.id] = subject as Subject;
        });
    }
}